"""Canonical success criteria from https://www.w3.org/TR/WCAG22/."""

# WCAG 2.2 removes obsolete Success Criterion 4.1.1.
WCAG22_CRITERIA = {
    '1.1.1': ('Non-text Content', 'non-text-content'),
    '1.2.1': ('Audio-only and Video-only (Prerecorded)', 'audio-only-and-video-only-prerecorded'),
    '1.2.2': ('Captions (Prerecorded)', 'captions-prerecorded'),
    '1.2.3': ('Audio Description or Media Alternative (Prerecorded)', 'audio-description-or-media-alternative-prerecorded'),
    '1.2.4': ('Captions (Live)', 'captions-live'),
    '1.2.5': ('Audio Description (Prerecorded)', 'audio-description-prerecorded'),
    '1.2.6': ('Sign Language (Prerecorded)', 'sign-language-prerecorded'),
    '1.2.7': ('Extended Audio Description (Prerecorded)', 'extended-audio-description-prerecorded'),
    '1.2.8': ('Media Alternative (Prerecorded)', 'media-alternative-prerecorded'),
    '1.2.9': ('Audio-only (Live)', 'audio-only-live'),
    '1.3.1': ('Info and Relationships', 'info-and-relationships'),
    '1.3.2': ('Meaningful Sequence', 'meaningful-sequence'),
    '1.3.3': ('Sensory Characteristics', 'sensory-characteristics'),
    '1.3.4': ('Orientation', 'orientation'),
    '1.3.5': ('Identify Input Purpose', 'identify-input-purpose'),
    '1.3.6': ('Identify Purpose', 'identify-purpose'),
    '1.4.1': ('Use of Color', 'use-of-color'),
    '1.4.2': ('Audio Control', 'audio-control'),
    '1.4.3': ('Contrast (Minimum)', 'contrast-minimum'),
    '1.4.4': ('Resize Text', 'resize-text'),
    '1.4.5': ('Images of Text', 'images-of-text'),
    '1.4.6': ('Contrast (Enhanced)', 'contrast-enhanced'),
    '1.4.7': ('Low or No Background Audio', 'low-or-no-background-audio'),
    '1.4.8': ('Visual Presentation', 'visual-presentation'),
    '1.4.9': ('Images of Text (No Exception)', 'images-of-text-no-exception'),
    '1.4.10': ('Reflow', 'reflow'),
    '1.4.11': ('Non-text Contrast', 'non-text-contrast'),
    '1.4.12': ('Text Spacing', 'text-spacing'),
    '1.4.13': ('Content on Hover or Focus', 'content-on-hover-or-focus'),
    '2.1.1': ('Keyboard', 'keyboard'),
    '2.1.2': ('No Keyboard Trap', 'no-keyboard-trap'),
    '2.1.3': ('Keyboard (No Exception)', 'keyboard-no-exception'),
    '2.1.4': ('Character Key Shortcuts', 'character-key-shortcuts'),
    '2.2.1': ('Timing Adjustable', 'timing-adjustable'),
    '2.2.2': ('Pause, Stop, Hide', 'pause-stop-hide'),
    '2.2.3': ('No Timing', 'no-timing'),
    '2.2.4': ('Interruptions', 'interruptions'),
    '2.2.5': ('Re-authenticating', 're-authenticating'),
    '2.2.6': ('Timeouts', 'timeouts'),
    '2.3.1': ('Three Flashes or Below Threshold', 'three-flashes-or-below-threshold'),
    '2.3.2': ('Three Flashes', 'three-flashes'),
    '2.3.3': ('Animation from Interactions', 'animation-from-interactions'),
    '2.4.1': ('Bypass Blocks', 'bypass-blocks'),
    '2.4.2': ('Page Titled', 'page-titled'),
    '2.4.3': ('Focus Order', 'focus-order'),
    '2.4.4': ('Link Purpose (In Context)', 'link-purpose-in-context'),
    '2.4.5': ('Multiple Ways', 'multiple-ways'),
    '2.4.6': ('Headings and Labels', 'headings-and-labels'),
    '2.4.7': ('Focus Visible', 'focus-visible'),
    '2.4.8': ('Location', 'location'),
    '2.4.9': ('Link Purpose (Link Only)', 'link-purpose-link-only'),
    '2.4.10': ('Section Headings', 'section-headings'),
    '2.4.11': ('Focus Not Obscured (Minimum)', 'focus-not-obscured-minimum'),
    '2.4.12': ('Focus Not Obscured (Enhanced)', 'focus-not-obscured-enhanced'),
    '2.4.13': ('Focus Appearance', 'focus-appearance'),
    '2.5.1': ('Pointer Gestures', 'pointer-gestures'),
    '2.5.2': ('Pointer Cancellation', 'pointer-cancellation'),
    '2.5.3': ('Label in Name', 'label-in-name'),
    '2.5.4': ('Motion Actuation', 'motion-actuation'),
    '2.5.5': ('Target Size (Enhanced)', 'target-size-enhanced'),
    '2.5.6': ('Concurrent Input Mechanisms', 'concurrent-input-mechanisms'),
    '2.5.7': ('Dragging Movements', 'dragging-movements'),
    '2.5.8': ('Target Size (Minimum)', 'target-size-minimum'),
    '3.1.1': ('Language of Page', 'language-of-page'),
    '3.1.2': ('Language of Parts', 'language-of-parts'),
    '3.1.3': ('Unusual Words', 'unusual-words'),
    '3.1.4': ('Abbreviations', 'abbreviations'),
    '3.1.5': ('Reading Level', 'reading-level'),
    '3.1.6': ('Pronunciation', 'pronunciation'),
    '3.2.1': ('On Focus', 'on-focus'),
    '3.2.2': ('On Input', 'on-input'),
    '3.2.3': ('Consistent Navigation', 'consistent-navigation'),
    '3.2.4': ('Consistent Identification', 'consistent-identification'),
    '3.2.5': ('Change on Request', 'change-on-request'),
    '3.2.6': ('Consistent Help', 'consistent-help'),
    '3.3.1': ('Error Identification', 'error-identification'),
    '3.3.2': ('Labels or Instructions', 'labels-or-instructions'),
    '3.3.3': ('Error Suggestion', 'error-suggestion'),
    '3.3.4': ('Error Prevention (Legal, Financial, Data)', 'error-prevention-legal-financial-data'),
    '3.3.5': ('Help', 'help'),
    '3.3.6': ('Error Prevention (All)', 'error-prevention-all'),
    '3.3.7': ('Redundant Entry', 'redundant-entry'),
    '3.3.8': ('Accessible Authentication (Minimum)', 'accessible-authentication-minimum'),
    '3.3.9': ('Accessible Authentication (Enhanced)', 'accessible-authentication-enhanced'),
    '4.1.2': ('Name, Role, Value', 'name-role-value'),
    '4.1.3': ('Status Messages', 'status-messages'),
}
